config/routes.rb
AthletePreneur::Application.routes.draw do
  resources :friendships

  resources :posts

  match '/auth/:provider/callback' => 'authentications#create'
  
  resources :authentications
  root :to => "posts#index"
  
  devise_for :users, :controllers => {:registrations => 'registrations'}
  
  devise_scope :user do
      match "users" => "registrations#index", :as => "users"
      match "show_user/:id" => "registrations#show", :as => "show_user"
      match "verify_user" => "registrations#verify_user", :as => "verify_user"
      match "update_verify_user" => "registrations#update_verify_user", :as => "update_verify_user"
      match "admin_verify_user" => "registrations#admin_verify_user", :as => "admin_verify_user"
      match "admin_update_verify_user" => "registrations#admin_update_verify_user", :as => "admin_update_verify_user"
  end
  
  match "main_search" => "posts#main_search"
end

app/views/shared/_companies.html.erb
<div class="company_wrapper">
<% @companies.each do |company| %>
  <div class="single_company_wrapper">
    <div class="single_company_image"><%= link_to image_tag(company.photo.url(:large_icon)), show_user_path(company), :class => 'image_link' %></div>
    <div class="single_company_name"><%= link_to username(company), show_user_path(company) %></div>
  </div>
<% end %>
</div>
	
	

app/views/shared/_header_nav.html.erb
<div class="navigation"> 
  <!------------------------------     Nav Left     ------------------------------>  
  <div class="nav_left">
    <%= link_to image_tag('Athletepreneur2logo255x44.png', :class => 'logo'), root_path %>
  </div>
  <!------------------------------     End Nav Left     ------------------------------>

  <% if params[:controller] != 'authentications' %>
  <% if user_signed_in? %>
       
    <!------------------------------     Logged In Nav Center     ------------------------------>
    <div class="nav_center">
       <%= form_tag main_search_path, :method => 'get', :id => "main_search" do %>
         <p>
           <%= text_field_tag :search, params[:search], :class => 'search_input', :placeholder => 'Search for Users' %>
           <%#= submit_tag "Search", :name => nil %>
         </p>
       <% end %>
     </div>
     <!------------------------------     End Logged In Nav Center     ------------------------------>
        
     <!------------------------------     Logged In Nav Right     ------------------------------>
     <div class="nav_right">
       <div class="nav_links">
         <%= link_to 'Home', root_path, :class => 'head' %> 
         &middot; <%= link_to 'Companies', main_search_path(:type => 'company'), :class => 'user_type_main_search head' %> 
         &middot; <%= link_to "Investors", main_search_path(:type => 'investor'), :class => 'user_type_main_search head' %>
         &middot; <%= link_to username(current_user), show_user_path(current_user), :class => 'head' %>
         &middot; <%= link_to "Logout", destroy_user_session_path, :class => 'head' %>
       </div>
     </div>
     <!------------------------------     End Logged In Nav Center     ------------------------------>
    
   <% else %>
  
    
     <!------------------------------     Not Logged In Nav Center     ------------------------------>
     <div class="nav_center">
       <div class="nav_links"><%= link_to 'Home', root_path, :class => 'header_selected head' %> &middot; <%= link_to 'Companies', main_search_path(:type => 'company'), :class => 'user_type_main_search head' %> &middot; <%= link_to "Investors", main_search_path(:type => 'investors'), :class => 'user_type_main_search head' %></div>
     </div>
     <!------------------------------     End Not Logged In Nav Center     ------------------------------>
        
     <!------------------------------     Not Logged In Nav Right     ------------------------------>
     <div class="nav_right">
       <div><%= link_to "Join", authentications_path, :class => 'head' %> &middot; <%= link_to "Login", authentications_path, :class => 'head' %></div>
     </div>
     <!------------------------------     End Not Logged In Nav Center     ------------------------------>
    
   <% end %>
   <% end %>
    
    
</div>

app/views/shared/_search.html.erb
<div class="search_wrapper">
  <% @search.each do |a| %>
    <div class="search_item_wrapper">
      <div class="search_image">
        <%= link_to image_tag(a.photo.url(:icon)), show_user_path(a) %>
      </div>
      <div class="search_name">
        <%= link_to username(a), show_user_path(a) %>
      </div>
    <% end %>
  </div>
</div>