config/routes.rb
AthletePreneur::Application.routes.draw do
  resources :friendships

  resources :posts

  match '/auth/:provider/callback' => 'authentications#create'
  
  resources :authentications
  root :to => "posts#index"
  
  devise_for :users, :controllers => {:registrations => 'registrations'}
  
  devise_scope :user do
      match "users" => "registrations#index", :as => "users"
      match "show_user/:id" => "registrations#show", :as => "show_user"
      match "verify_user" => "registrations#verify_user", :as => "verify_user"
      match "update_verify_user" => "registrations#update_verify_user", :as => "update_verify_user"
      match "admin_verify_user" => "registrations#admin_verify_user", :as => "admin_verify_user"
      match "admin_update_verify_user" => "registrations#admin_update_verify_user", :as => "admin_update_verify_user"
  end
  
  match "main_search" => "posts#main_search"
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
  	  puts 'create'
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
    if @friendship.save
      flash[:notice] = "Added friend."
      redirect_to root_url
    else
      flash[:error] = "Unable to add friend."
      redirect_to root_url
    end
  end

  def destroy	  
    
    if params[:friend_id]
      @ff = current_user.friendships.find_by_friend_id(params[:friend_id])	  	  
    else  
      @ff = Friendship.find(params[:id])
    end
    
    if @ff.user_id == current_user.id 
      fid = @ff.friend_id  
      cid = @ff.user_id
    elsif @ff.friend_id == current_user.id
      fid = @ff.user_id
      cid = @ff.friend_id
    else
      flash[:notice] = "You do not have sufficient privileges."
      redirect_to show_user_path(current_user.id)
    end
    
    @friendship = Friendship.find(:first, :conditions => ['(user_id = ? AND friend_id = ?)', cid, fid])
    @friendship2 = Friendship.find(:first, :conditions => ['(user_id = ? AND friend_id = ?)', fid, cid])
    
    @friendship.destroy if !@friendship.nil?
    @friendship2.destroy if !@friendship2.nil?
    
    flash[:notice] = "Removed friendship."
    redirect_to show_user_path(current_user.id)
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.erb
<%= form_for(@friendship) do |f| %>
  <% if @friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% @friendship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :friend_id %><br />
    <%= f.text_field :friend_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<h1>Listing friendships</h1>

<table>
  <tr>
    <th>User</th>
    <th>Friend</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @friendships.each do |friendship| %>
  <tr>
    <td><%= friendship.user_id %></td>
    <td><%= friendship.friend_id %></td>
    <td><%= link_to 'Show', friendship %></td>
    <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
    <td><%= link_to 'Destroy', friendship, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Friendship', new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @friendship.user_id %>
</p>

<p>
  <b>Friend:</b>
  <%= @friendship.friend_id %>
</p>


<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>