config/routes.rb
AthletePreneur::Application.routes.draw do
  resources :friendships

  resources :posts

  match '/auth/:provider/callback' => 'authentications#create'
  
  resources :authentications
  root :to => "posts#index"
  
  devise_for :users, :controllers => {:registrations => 'registrations'}
  
  devise_scope :user do
      match "users" => "registrations#index", :as => "users"
      match "show_user/:id" => "registrations#show", :as => "show_user"
      match "verify_user" => "registrations#verify_user", :as => "verify_user"
      match "update_verify_user" => "registrations#update_verify_user", :as => "update_verify_user"
      match "admin_verify_user" => "registrations#admin_verify_user", :as => "admin_verify_user"
      match "admin_update_verify_user" => "registrations#admin_update_verify_user", :as => "admin_update_verify_user"
  end
  
  match "main_search" => "posts#main_search"
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :is_admin, :except => [:index, :show, :main_search]	
	
	
  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.find(:all, :order => 'created_at desc', :limit => 2)
    
    @posts.map do |a|
    	    icons = a.content.match(/\<img.*\/\>/).to_s.gsub(/\/content_/, '/large_icon_').gsub(/style=".*"/, '')
    	    a.content = a.content.gsub(/\<img.*\/\>/,'')
    	    a.content = html_truncate(a.content, 200)
    	    a.icon = icons
    end
    
    @companies = User.find(:all, :conditions => ['account_type LIKE ?', 'company'], :order => 'created_at desc') 

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])
    @post.user_id = current_user.id
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
  
  def main_search
    @search = User.search(params[:search], params[:type]) #.order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])	 
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %>
    <%= f.cktext_area :content, :height => 400, :swf_params => { :assetable_type => 'Test', :assetable_id => 1 } %>
    
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="post_header">
  From game plan to business plan
</div>


<div class="posts_wrapper">
 <% @posts.each do |post| %>
   <div class="post_div">
     <div class="post_image_div"><%= link_to post.icon.html_safe, post %></div>
     <div class="post_title_div"><%= link_to post.title, post %></div>
     <div class="post_content_div"><%= post.content.html_safe %></div>
     <div class="post_name_div"><%= username(post.user) %></div>
   </div>
 <% end %>
</div>

<% if !user_signed_in? %>
<div class="join_wrapper">
  <%= link_to 'Join AthletePreneur', authentications_path %>
</div>
<% end %>

app/views/posts/main_search.js.erb
$("#container").html("<%= escape_javascript(render("shared/search")) %>");

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div id="notice"><%= notice %></div>

<div>
  <b>Title:</b>
  <%= @post.title %>
</div>

<div class="post_content">
  <%= @post.content.html_safe %>
</div>

<div>
  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Back', posts_path %>
</div>