config/routes.rb
AthletePreneur::Application.routes.draw do
  resources :friendships

  resources :posts

  match '/auth/:provider/callback' => 'authentications#create'
  
  resources :authentications
  root :to => "posts#index"
  
  devise_for :users, :controllers => {:registrations => 'registrations'}
  
  devise_scope :user do
      match "users" => "registrations#index", :as => "users"
      match "show_user/:id" => "registrations#show", :as => "show_user"
      match "verify_user" => "registrations#verify_user", :as => "verify_user"
      match "update_verify_user" => "registrations#update_verify_user", :as => "update_verify_user"
      match "admin_verify_user" => "registrations#admin_verify_user", :as => "admin_verify_user"
      match "admin_update_verify_user" => "registrations#admin_update_verify_user", :as => "admin_update_verify_user"
  end
  
  match "main_search" => "posts#main_search"
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AthletePreneur</title>
    
    <%= stylesheet_link_tag "fancybox/jquery.fancybox-1.3.4.css", "application" %>
    <%= javascript_include_tag 'jquery', 'application' %>
    <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "fancybox/jquery.fancybox-1.3.4.pack.js" %>
    <%= javascript_include_tag "/javascripts/ckeditor/ckeditor.js" %>
    <%= javascript_include_tag 'rails' %>
    <%= csrf_meta_tag %>
    <link rel="Icon" href="/images/apfavicon.png" type="image/x-icon">
    
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-2677869-15']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  
  </script>
    
  </head>
  <body>
  
  <%= render 'shared/header_nav' %>
  
  <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      
      <%= content_tag :h1, yield(:title) if show_title? %>
      
      <%= yield %>
  </div>
  
  <% if params[:controller] == 'posts' && params[:action] == 'index' %>
    <%= render 'shared/companies' %>
  <% end %>
    
  <% if is_admin? %>
    <div class="footer">
      <%= link_to 'Verify Users', admin_verify_user_path %>  &middot; <%= link_to 'New Post', new_post_path %>
    </div>
  <% end %>
  
  </body>
</html>